# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(773, 559)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 751, 511))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.formLayoutWidget = QtGui.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 340, 731, 141))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.modKey = QtGui.QComboBox(self.formLayoutWidget)
        self.modKey.setObjectName(_fromUtf8("modKey"))
        self.modKey.addItem(_fromUtf8(""))
        self.modKey.addItem(_fromUtf8(""))
        self.modKey.addItem(_fromUtf8(""))
        self.modKey.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.modKey)
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.floatingKey = QtGui.QComboBox(self.formLayoutWidget)
        self.floatingKey.setObjectName(_fromUtf8("floatingKey"))
        self.floatingKey.addItem(_fromUtf8(""))
        self.floatingKey.addItem(_fromUtf8(""))
        self.floatingKey.addItem(_fromUtf8(""))
        self.floatingKey.addItem(_fromUtf8(""))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.floatingKey)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.orientation = QtGui.QComboBox(self.formLayoutWidget)
        self.orientation.setObjectName(_fromUtf8("orientation"))
        self.orientation.addItem(_fromUtf8(""))
        self.orientation.addItem(_fromUtf8(""))
        self.orientation.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.orientation)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.workspaceLayout = QtGui.QComboBox(self.formLayoutWidget)
        self.workspaceLayout.setObjectName(_fromUtf8("workspaceLayout"))
        self.workspaceLayout.addItem(_fromUtf8(""))
        self.workspaceLayout.addItem(_fromUtf8(""))
        self.workspaceLayout.addItem(_fromUtf8(""))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.workspaceLayout)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.borders = QtGui.QComboBox(self.formLayoutWidget)
        self.borders.setObjectName(_fromUtf8("borders"))
        self.borders.addItem(_fromUtf8(""))
        self.borders.addItem(_fromUtf8(""))
        self.borders.addItem(_fromUtf8(""))
        self.borders.addItem(_fromUtf8(""))
        self.borders.addItem(_fromUtf8(""))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.borders)
        self.textBrowser = QtGui.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 731, 321))
        self.textBrowser.setStyleSheet(_fromUtf8("background: transparent;"))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 721, 171))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 111, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.windowFocusIndicator = QtGui.QLineEdit(self.groupBox)
        self.windowFocusIndicator.setGeometry(QtCore.QRect(520, 40, 121, 20))
        self.windowFocusIndicator.setObjectName(_fromUtf8("windowFocusIndicator"))
        self.windowFocusBorder = QtGui.QLineEdit(self.groupBox)
        self.windowFocusBorder.setGeometry(QtCore.QRect(130, 40, 121, 20))
        self.windowFocusBorder.setObjectName(_fromUtf8("windowFocusBorder"))
        self.windowFocusBackground = QtGui.QLineEdit(self.groupBox)
        self.windowFocusBackground.setGeometry(QtCore.QRect(260, 40, 121, 20))
        self.windowFocusBackground.setObjectName(_fromUtf8("windowFocusBackground"))
        self.windowFocusText = QtGui.QLineEdit(self.groupBox)
        self.windowFocusText.setGeometry(QtCore.QRect(390, 40, 121, 20))
        self.windowFocusText.setObjectName(_fromUtf8("windowFocusText"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 111, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 100, 111, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 130, 111, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.windowUnfocusBorder = QtGui.QLineEdit(self.groupBox)
        self.windowUnfocusBorder.setGeometry(QtCore.QRect(130, 70, 121, 20))
        self.windowUnfocusBorder.setObjectName(_fromUtf8("windowUnfocusBorder"))
        self.windowUnfocusText = QtGui.QLineEdit(self.groupBox)
        self.windowUnfocusText.setGeometry(QtCore.QRect(390, 70, 121, 20))
        self.windowUnfocusText.setObjectName(_fromUtf8("windowUnfocusText"))
        self.windowUnfocusIndicator = QtGui.QLineEdit(self.groupBox)
        self.windowUnfocusIndicator.setGeometry(QtCore.QRect(520, 70, 121, 20))
        self.windowUnfocusIndicator.setObjectName(_fromUtf8("windowUnfocusIndicator"))
        self.windowUnfocusBackground = QtGui.QLineEdit(self.groupBox)
        self.windowUnfocusBackground.setGeometry(QtCore.QRect(260, 70, 121, 20))
        self.windowUnfocusBackground.setObjectName(_fromUtf8("windowUnfocusBackground"))
        self.windowInactiveBorder = QtGui.QLineEdit(self.groupBox)
        self.windowInactiveBorder.setGeometry(QtCore.QRect(130, 100, 121, 20))
        self.windowInactiveBorder.setObjectName(_fromUtf8("windowInactiveBorder"))
        self.windowInactiveText = QtGui.QLineEdit(self.groupBox)
        self.windowInactiveText.setGeometry(QtCore.QRect(390, 100, 121, 20))
        self.windowInactiveText.setObjectName(_fromUtf8("windowInactiveText"))
        self.windowInactiveIndicator = QtGui.QLineEdit(self.groupBox)
        self.windowInactiveIndicator.setGeometry(QtCore.QRect(520, 100, 121, 20))
        self.windowInactiveIndicator.setObjectName(_fromUtf8("windowInactiveIndicator"))
        self.windowInactiveBackground = QtGui.QLineEdit(self.groupBox)
        self.windowInactiveBackground.setGeometry(QtCore.QRect(260, 100, 121, 20))
        self.windowInactiveBackground.setObjectName(_fromUtf8("windowInactiveBackground"))
        self.windowUrgentBorder = QtGui.QLineEdit(self.groupBox)
        self.windowUrgentBorder.setGeometry(QtCore.QRect(130, 130, 121, 20))
        self.windowUrgentBorder.setObjectName(_fromUtf8("windowUrgentBorder"))
        self.windowUrgentText = QtGui.QLineEdit(self.groupBox)
        self.windowUrgentText.setGeometry(QtCore.QRect(390, 130, 121, 20))
        self.windowUrgentText.setObjectName(_fromUtf8("windowUrgentText"))
        self.windowUrgentIndicator = QtGui.QLineEdit(self.groupBox)
        self.windowUrgentIndicator.setGeometry(QtCore.QRect(520, 130, 121, 20))
        self.windowUrgentIndicator.setObjectName(_fromUtf8("windowUrgentIndicator"))
        self.windowUrgentBackground = QtGui.QLineEdit(self.groupBox)
        self.windowUrgentBackground.setGeometry(QtCore.QRect(260, 130, 121, 20))
        self.windowUrgentBackground.setObjectName(_fromUtf8("windowUrgentBackground"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(130, 20, 121, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(260, 20, 121, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(390, 20, 121, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(520, 20, 121, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 190, 721, 281))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 701, 81))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_14 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.barBackground = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.barBackground.setObjectName(_fromUtf8("barBackground"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.barBackground)
        self.label_15 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.barStatus = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.barStatus.setObjectName(_fromUtf8("barStatus"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.barStatus)
        self.label_16 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_16)
        self.barSeparator = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.barSeparator.setObjectName(_fromUtf8("barSeparator"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.barSeparator)
        self.barActiveBackground = QtGui.QLineEdit(self.groupBox_2)
        self.barActiveBackground.setGeometry(QtCore.QRect(290, 160, 121, 20))
        self.barActiveBackground.setObjectName(_fromUtf8("barActiveBackground"))
        self.label_21 = QtGui.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(20, 220, 131, 20))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.barFocusBackground = QtGui.QLineEdit(self.groupBox_2)
        self.barFocusBackground.setGeometry(QtCore.QRect(290, 130, 121, 20))
        self.barFocusBackground.setObjectName(_fromUtf8("barFocusBackground"))
        self.barActiveBorder = QtGui.QLineEdit(self.groupBox_2)
        self.barActiveBorder.setGeometry(QtCore.QRect(160, 160, 121, 20))
        self.barActiveBorder.setObjectName(_fromUtf8("barActiveBorder"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(20, 130, 131, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.barFocusBorder = QtGui.QLineEdit(self.groupBox_2)
        self.barFocusBorder.setGeometry(QtCore.QRect(160, 130, 121, 20))
        self.barFocusBorder.setObjectName(_fromUtf8("barFocusBorder"))
        self.barUrgentText = QtGui.QLineEdit(self.groupBox_2)
        self.barUrgentText.setGeometry(QtCore.QRect(420, 220, 121, 20))
        self.barUrgentText.setObjectName(_fromUtf8("barUrgentText"))
        self.barUrgentBackground = QtGui.QLineEdit(self.groupBox_2)
        self.barUrgentBackground.setGeometry(QtCore.QRect(290, 220, 121, 20))
        self.barUrgentBackground.setObjectName(_fromUtf8("barUrgentBackground"))
        self.barUrgentBorder = QtGui.QLineEdit(self.groupBox_2)
        self.barUrgentBorder.setGeometry(QtCore.QRect(160, 220, 121, 20))
        self.barUrgentBorder.setObjectName(_fromUtf8("barUrgentBorder"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(160, 110, 121, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.barInactiveBorder = QtGui.QLineEdit(self.groupBox_2)
        self.barInactiveBorder.setGeometry(QtCore.QRect(160, 190, 121, 20))
        self.barInactiveBorder.setObjectName(_fromUtf8("barInactiveBorder"))
        self.barInactiveText = QtGui.QLineEdit(self.groupBox_2)
        self.barInactiveText.setGeometry(QtCore.QRect(420, 190, 121, 20))
        self.barInactiveText.setObjectName(_fromUtf8("barInactiveText"))
        self.barActiveText = QtGui.QLineEdit(self.groupBox_2)
        self.barActiveText.setGeometry(QtCore.QRect(420, 160, 121, 20))
        self.barActiveText.setObjectName(_fromUtf8("barActiveText"))
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(430, 110, 121, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(20, 190, 131, 20))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.barInactiveBackground = QtGui.QLineEdit(self.groupBox_2)
        self.barInactiveBackground.setGeometry(QtCore.QRect(290, 190, 121, 20))
        self.barInactiveBackground.setObjectName(_fromUtf8("barInactiveBackground"))
        self.barFocusText = QtGui.QLineEdit(self.groupBox_2)
        self.barFocusText.setGeometry(QtCore.QRect(420, 130, 121, 20))
        self.barFocusText.setObjectName(_fromUtf8("barFocusText"))
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(20, 160, 131, 20))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_19 = QtGui.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(290, 110, 121, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(20, 250, 131, 20))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.barModeBorder = QtGui.QLineEdit(self.groupBox_2)
        self.barModeBorder.setGeometry(QtCore.QRect(160, 250, 121, 20))
        self.barModeBorder.setObjectName(_fromUtf8("barModeBorder"))
        self.barModeBackground = QtGui.QLineEdit(self.groupBox_2)
        self.barModeBackground.setGeometry(QtCore.QRect(290, 250, 121, 20))
        self.barModeBackground.setObjectName(_fromUtf8("barModeBackground"))
        self.barModeText = QtGui.QLineEdit(self.groupBox_2)
        self.barModeText.setGeometry(QtCore.QRect(420, 250, 121, 20))
        self.barModeText.setObjectName(_fromUtf8("barModeText"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.workspacesTable = QtGui.QTableWidget(self.tab_3)
        self.workspacesTable.setGeometry(QtCore.QRect(10, 10, 731, 441))
        self.workspacesTable.setProperty("showDropIndicator", False)
        self.workspacesTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.workspacesTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.workspacesTable.setObjectName(_fromUtf8("workspacesTable"))
        self.workspacesTable.setColumnCount(2)
        self.workspacesTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.workspacesTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.workspacesTable.setHorizontalHeaderItem(1, item)
        self.formLayoutWidget_5 = QtGui.QWidget(self.tab_3)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 460, 281, 22))
        self.formLayoutWidget_5.setObjectName(_fromUtf8("formLayoutWidget_5"))
        self.formLayout_10 = QtGui.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_10.setMargin(0)
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.label_36 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_36)
        self.workspaceName = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.workspaceName.setObjectName(_fromUtf8("workspaceName"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.workspaceName)
        self.btnInsertWorkspace = QtGui.QPushButton(self.tab_3)
        self.btnInsertWorkspace.setGeometry(QtCore.QRect(660, 460, 81, 21))
        self.btnInsertWorkspace.setObjectName(_fromUtf8("btnInsertWorkspace"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.appsTable = QtGui.QTableWidget(self.tab_4)
        self.appsTable.setGeometry(QtCore.QRect(10, 10, 731, 401))
        self.appsTable.setObjectName(_fromUtf8("appsTable"))
        self.appsTable.setColumnCount(7)
        self.appsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.appsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.appsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.appsTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.appsTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.appsTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.appsTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.appsTable.setHorizontalHeaderItem(6, item)
        self.formLayoutWidget_6 = QtGui.QWidget(self.tab_4)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(10, 420, 191, 51))
        self.formLayoutWidget_6.setObjectName(_fromUtf8("formLayoutWidget_6"))
        self.formLayout_6 = QtGui.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setMargin(0)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_28 = QtGui.QLabel(self.formLayoutWidget_6)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_28)
        self.appName = QtGui.QLineEdit(self.formLayoutWidget_6)
        self.appName.setObjectName(_fromUtf8("appName"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.appName)
        self.label_27 = QtGui.QLabel(self.formLayoutWidget_6)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_27)
        self.appClass = QtGui.QLineEdit(self.formLayoutWidget_6)
        self.appClass.setObjectName(_fromUtf8("appClass"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.appClass)
        self.pushButton_5 = QtGui.QPushButton(self.tab_4)
        self.pushButton_5.setGeometry(QtCore.QRect(680, 420, 61, 51))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.formLayoutWidget_7 = QtGui.QWidget(self.tab_4)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(210, 420, 251, 51))
        self.formLayoutWidget_7.setObjectName(_fromUtf8("formLayoutWidget_7"))
        self.formLayout_7 = QtGui.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setMargin(0)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.label_29 = QtGui.QLabel(self.formLayoutWidget_7)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_29)
        self.appHotkey = QtGui.QLineEdit(self.formLayoutWidget_7)
        self.appHotkey.setObjectName(_fromUtf8("appHotkey"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.appHotkey)
        self.label_32 = QtGui.QLabel(self.formLayoutWidget_7)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_32)
        self.appWorkspace = QtGui.QComboBox(self.formLayoutWidget_7)
        self.appWorkspace.setObjectName(_fromUtf8("appWorkspace"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.appWorkspace)
        self.formLayoutWidget_8 = QtGui.QWidget(self.tab_4)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(470, 420, 200, 51))
        self.formLayoutWidget_8.setObjectName(_fromUtf8("formLayoutWidget_8"))
        self.formLayout_9 = QtGui.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_9.setMargin(0)
        self.formLayout_9.setObjectName(_fromUtf8("formLayout_9"))
        self.label_33 = QtGui.QLabel(self.formLayoutWidget_8)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_33)
        self.label_34 = QtGui.QLabel(self.formLayoutWidget_8)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_34)
        self.appMove = QtGui.QComboBox(self.formLayoutWidget_8)
        self.appMove.setObjectName(_fromUtf8("appMove"))
        self.appMove.addItem(_fromUtf8(""))
        self.appMove.addItem(_fromUtf8(""))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.FieldRole, self.appMove)
        self.appFloating = QtGui.QComboBox(self.formLayoutWidget_8)
        self.appFloating.setObjectName(_fromUtf8("appFloating"))
        self.appFloating.addItem(_fromUtf8(""))
        self.appFloating.addItem(_fromUtf8(""))
        self.appFloating.addItem(_fromUtf8(""))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.appFloating)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.keyboardTable = QtGui.QTableWidget(self.tab_6)
        self.keyboardTable.setGeometry(QtCore.QRect(10, 10, 731, 431))
        self.keyboardTable.setObjectName(_fromUtf8("keyboardTable"))
        self.keyboardTable.setColumnCount(3)
        self.keyboardTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.keyboardTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.keyboardTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.keyboardTable.setHorizontalHeaderItem(2, item)
        self.formLayoutWidget_3 = QtGui.QWidget(self.tab_6)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 450, 211, 22))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_20 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_20)
        self.keyboardHotkey = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.keyboardHotkey.setObjectName(_fromUtf8("keyboardHotkey"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.keyboardHotkey)
        self.formLayoutWidget_4 = QtGui.QWidget(self.tab_6)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(230, 450, 421, 22))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.keyboardAction = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.keyboardAction.setObjectName(_fromUtf8("keyboardAction"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.keyboardAction)
        self.label_26 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_26)
        self.btnKeyboardInsert = QtGui.QPushButton(self.tab_6)
        self.btnKeyboardInsert.setGeometry(QtCore.QRect(660, 450, 81, 21))
        self.btnKeyboardInsert.setObjectName(_fromUtf8("btnKeyboardInsert"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.modesTab = QtGui.QTabWidget(self.tab_7)
        self.modesTab.setGeometry(QtCore.QRect(10, 10, 731, 441))
        self.modesTab.setObjectName(_fromUtf8("modesTab"))
        self.btnModeInsert = QtGui.QPushButton(self.tab_7)
        self.btnModeInsert.setGeometry(QtCore.QRect(300, 460, 81, 21))
        self.btnModeInsert.setObjectName(_fromUtf8("btnModeInsert"))
        self.formLayoutWidget_11 = QtGui.QWidget(self.tab_7)
        self.formLayoutWidget_11.setGeometry(QtCore.QRect(10, 460, 281, 22))
        self.formLayoutWidget_11.setObjectName(_fromUtf8("formLayoutWidget_11"))
        self.formLayout_13 = QtGui.QFormLayout(self.formLayoutWidget_11)
        self.formLayout_13.setMargin(0)
        self.formLayout_13.setObjectName(_fromUtf8("formLayout_13"))
        self.label_39 = QtGui.QLabel(self.formLayoutWidget_11)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_39)
        self.modeName = QtGui.QLineEdit(self.formLayoutWidget_11)
        self.modeName.setObjectName(_fromUtf8("modeName"))
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.FieldRole, self.modeName)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.startupTable = QtGui.QTableWidget(self.tab_8)
        self.startupTable.setGeometry(QtCore.QRect(10, 10, 731, 441))
        self.startupTable.setProperty("showDropIndicator", False)
        self.startupTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.startupTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.startupTable.setObjectName(_fromUtf8("startupTable"))
        self.startupTable.setColumnCount(2)
        self.startupTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.startupTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.startupTable.setHorizontalHeaderItem(1, item)
        self.btnStartupInsert = QtGui.QPushButton(self.tab_8)
        self.btnStartupInsert.setGeometry(QtCore.QRect(660, 460, 81, 21))
        self.btnStartupInsert.setObjectName(_fromUtf8("btnStartupInsert"))
        self.formLayoutWidget_12 = QtGui.QWidget(self.tab_8)
        self.formLayoutWidget_12.setGeometry(QtCore.QRect(10, 460, 281, 22))
        self.formLayoutWidget_12.setObjectName(_fromUtf8("formLayoutWidget_12"))
        self.formLayout_14 = QtGui.QFormLayout(self.formLayoutWidget_12)
        self.formLayout_14.setMargin(0)
        self.formLayout_14.setObjectName(_fromUtf8("formLayout_14"))
        self.label_40 = QtGui.QLabel(self.formLayoutWidget_12)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.formLayout_14.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_40)
        self.startupCommand = QtGui.QLineEdit(self.formLayoutWidget_12)
        self.startupCommand.setObjectName(_fromUtf8("startupCommand"))
        self.formLayout_14.setWidget(0, QtGui.QFormLayout.FieldRole, self.startupCommand)
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.btnSave = QtGui.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(620, 530, 141, 24))
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.btnRefresh = QtGui.QPushButton(self.centralwidget)
        self.btnRefresh.setGeometry(QtCore.QRect(90, 530, 91, 24))
        self.btnRefresh.setObjectName(_fromUtf8("btnRefresh"))
        self.btnQuit = QtGui.QPushButton(self.centralwidget)
        self.btnQuit.setGeometry(QtCore.QRect(10, 530, 71, 24))
        self.btnQuit.setObjectName(_fromUtf8("btnQuit"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "i3 Manager", None))
        self.modKey.setItemText(0, _translate("MainWindow", "Alt", None))
        self.modKey.setItemText(1, _translate("MainWindow", "Super", None))
        self.modKey.setItemText(2, _translate("MainWindow", "CTRL", None))
        self.modKey.setItemText(3, _translate("MainWindow", "Shift", None))
        self.label.setText(_translate("MainWindow", "Modifier Key", None))
        self.label_2.setText(_translate("MainWindow", "Floating Modifier", None))
        self.floatingKey.setItemText(0, _translate("MainWindow", "Alt", None))
        self.floatingKey.setItemText(1, _translate("MainWindow", "Super", None))
        self.floatingKey.setItemText(2, _translate("MainWindow", "CTRL", None))
        self.floatingKey.setItemText(3, _translate("MainWindow", "Shift", None))
        self.label_3.setText(_translate("MainWindow", "Default Orientation", None))
        self.orientation.setItemText(0, _translate("MainWindow", "Horizontal", None))
        self.orientation.setItemText(1, _translate("MainWindow", "Vertical", None))
        self.orientation.setItemText(2, _translate("MainWindow", "Auto", None))
        self.label_4.setText(_translate("MainWindow", "Workspace Layout", None))
        self.workspaceLayout.setItemText(0, _translate("MainWindow", "Default", None))
        self.workspaceLayout.setItemText(1, _translate("MainWindow", "Tabbed", None))
        self.workspaceLayout.setItemText(2, _translate("MainWindow", "Stacking", None))
        self.label_5.setText(_translate("MainWindow", "Hide Edge Borders", None))
        self.borders.setItemText(0, _translate("MainWindow", "None", None))
        self.borders.setItemText(1, _translate("MainWindow", "Vertical", None))
        self.borders.setItemText(2, _translate("MainWindow", "Horizontal", None))
        self.borders.setItemText(3, _translate("MainWindow", "Both", None))
        self.borders.setItemText(4, _translate("MainWindow", "Smart", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt;\">i3 Manager</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Author: Eray Aydın &lt;eray@labkod.com&gt; (https://erayaydin.github.io)</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "General", None))
        self.groupBox.setTitle(_translate("MainWindow", "Window Decoration", None))
        self.label_6.setText(_translate("MainWindow", "Focused", None))
        self.label_7.setText(_translate("MainWindow", "Unfocused", None))
        self.label_8.setText(_translate("MainWindow", "Focused Inactive", None))
        self.label_9.setText(_translate("MainWindow", "Urgent", None))
        self.label_10.setText(_translate("MainWindow", "Border Color", None))
        self.label_11.setText(_translate("MainWindow", "Background", None))
        self.label_12.setText(_translate("MainWindow", "Text Color", None))
        self.label_13.setText(_translate("MainWindow", "Indicator", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "i3 Bar", None))
        self.label_14.setText(_translate("MainWindow", "Background", None))
        self.label_15.setText(_translate("MainWindow", "Status Line Text Color", None))
        self.label_16.setText(_translate("MainWindow", "Bar Separator Text Color", None))
        self.label_21.setText(_translate("MainWindow", "Urgent Workspace", None))
        self.label_18.setText(_translate("MainWindow", "Focused Workspace", None))
        self.label_17.setText(_translate("MainWindow", "Border Color", None))
        self.label_22.setText(_translate("MainWindow", "Text Color", None))
        self.label_23.setText(_translate("MainWindow", "Inactive Workspace", None))
        self.label_24.setText(_translate("MainWindow", "Active Workspace", None))
        self.label_19.setText(_translate("MainWindow", "Background", None))
        self.label_25.setText(_translate("MainWindow", "Mode", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Theme", None))
        item = self.workspacesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Workspace Name", None))
        item = self.workspacesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Remove", None))
        self.label_36.setText(_translate("MainWindow", "Workspace Name", None))
        self.btnInsertWorkspace.setText(_translate("MainWindow", "Insert", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Workspaces", None))
        item = self.appsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Application", None))
        item = self.appsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Class", None))
        item = self.appsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Start Hotkey", None))
        item = self.appsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Target Workspace", None))
        item = self.appsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Floating", None))
        item = self.appsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Move", None))
        item = self.appsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Remove", None))
        self.label_28.setText(_translate("MainWindow", "Application", None))
        self.label_27.setText(_translate("MainWindow", "Class", None))
        self.pushButton_5.setText(_translate("MainWindow", "Insert", None))
        self.label_29.setText(_translate("MainWindow", "Start Hotkey", None))
        self.label_32.setText(_translate("MainWindow", "Target Workspace", None))
        self.label_33.setText(_translate("MainWindow", "Floating", None))
        self.label_34.setText(_translate("MainWindow", "Move", None))
        self.appMove.setItemText(0, _translate("MainWindow", "None", None))
        self.appMove.setItemText(1, _translate("MainWindow", "Force Move Center", None))
        self.appFloating.setItemText(0, _translate("MainWindow", "None", None))
        self.appFloating.setItemText(1, _translate("MainWindow", "Force Enable", None))
        self.appFloating.setItemText(2, _translate("MainWindow", "Force Disable", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "App Bindings", None))
        item = self.keyboardTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hotkey", None))
        item = self.keyboardTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Action", None))
        item = self.keyboardTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Remove", None))
        self.label_20.setText(_translate("MainWindow", "Hotkey", None))
        self.label_26.setText(_translate("MainWindow", "Action", None))
        self.btnKeyboardInsert.setText(_translate("MainWindow", "Insert", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Keyboard Bindings", None))
        self.btnModeInsert.setText(_translate("MainWindow", "Insert", None))
        self.label_39.setText(_translate("MainWindow", "Mode Name", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Modes", None))
        item = self.startupTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Command", None))
        item = self.startupTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Remove", None))
        self.btnStartupInsert.setText(_translate("MainWindow", "Insert", None))
        self.label_40.setText(_translate("MainWindow", "Command", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Startup", None))
        self.btnSave.setText(_translate("MainWindow", "Save Configuration", None))
        self.btnRefresh.setText(_translate("MainWindow", "Refresh", None))
        self.btnQuit.setText(_translate("MainWindow", "Quit", None))

